id: IF777BAA5
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 17:57:39.919703+00:00
last_modified: 2022-12-14 17:57:39.919712+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-094-013
  eft-text-version: 1.1.2 2020
  title: Toh_736-The_Dharani_of_Parnasavari-v2
bases:
  BE9C:
    source_metadata: null
    order: 1
    base_file: BE9C.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
